# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Java
      run: sudo apt install openjdk-17-jdk
    
    - name: Install Gradle
      run: sudo apt install gradle

    - name: go to app
      run: cd app

    - name: Build with Gradle
      run: gradle build
    
    - name: setup docker
      run: sudo apt-get install ca-certificates curl gnupg lsb-release
    
    - name: mkdir keyrings
      run: sudo mkdir -p /etc/apt/keyrings
    
    - name: curl docker repository
      run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.g
   
    - name: set repository
      run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null 
   
    - name: download docker
      run: sudo apt-get install docker-ce docker-ce-cli
    
    - name: publish in docker registry
      run: docker build -t ssimiao/cowboybepop-api -f app/Dockerfile
    
    - name: login in docker
      run: docker login --username $REG_USERNAME --password $REG_PASSWORD
    
    - name: publish in docker registry
      run: docker push ssimiao/cowboybepop-api
