# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        gradle-version: '7.2'
    
    - name: download docker
      run: sudo apt-get install docker-ce docker-ce-cli
    
    - name: publish in docker registry
      run: docker build -t ssimiao/cowboybepop-api -f app/Dockerfile
    
    - name: login in docker
      run: docker login --username $REG_USERNAME --password $REG_PASSWORD
    
    - name: publish in docker registry
      run: docker push ssimiao/cowboybepop-api
