# This is a basic workflow to help you get started with Actions
 
name:
  Stop application
 
on:
  schedule:
    - cron: "0 22 * * *"
 
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: curl stop application
        run: curl -X POST https://cowboybepop.up.railway.app/actuator/shutdown
